### ISSUE TITLE
PBF NodeID bits in PackedVector

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#114]
Previously we changed the bits of `NodeID` to `63` in `PackedVector` to adaptor telenav PBF:
https://github.com/Telenav/osrm-backend/blob/6283c6074066f98e6d4a9f774f21ea45407c0d52/include/extractor/packed_osm_ids.hpp#L14
by PR https://github.com/Telenav/osrm-backend/pull/15/files

But by discussion https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/packed_vector.md#others, use `63` bits in `PackedVector` is ineffenciency. 

Maybe we can shrink telenav PBF's NodeID to `33` bits by some simple preprocess? So we can get the `33` bits back, same with in OSM PBF. 

@CodeBear801  How's your opinion?

**Comment by CodeBear801** [comment]
Preprocess PBF's NodeID and make which inside the range of 33 bits is possible.  
Which means:
- During iterating PBF, we create a 1 to 1 mapping for original node id, start from 1, incremental the value when met new node id for navigable links
- Replace original node id with new node id
- Replace node id exists in ways, node id tag
- Replace node id inside relations, in relation member
- Such mapping table need to be recorded, because we want to have the ability to convert back for debug/tracing purpose.

The task mainly related with pbf processing.

**Comment by wangyoucao577** [comment]
Oh..I thought the internal PBF's NodeID is just a simple `32bits` num plus some extra flag, similar with `100`. If it's not, I think it's unnecessary to process it. Let's keep `63bits` unless performance/memory inacceptable.
