### ISSUE TITLE
Add new services of Oasis

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#121]
This issue is sub-task of #120 

Before start work on Oasis, want to confirm with Jay on following items:
- Reference project could be osrm-ranking
- Add new folder in `integration/cmd`, the main function and flags' handling will be there.  Need to define `listenPort` and `osrmBackendEndpoint`.  `osrmBackendEndpoint` could be on the same machine for initial version?
- Now `integration/pkg/api` mainly deal with request/response related with OSRM.  If I want to add request/response for oasis, should I add folder of `integration/pkg/api/oasis` and put `Request` and `Response`'s code there?
- The main logic should should be in `integration/oasis`, which will communicate with OSRM->table service(need add) and calculate best charge station
  - routeByOSRM/tableByOSRM could be put into `integration/pkg/api/service` for later?
- Oasis service might need communicate with search service, if so, will also put related code in `integration/pkg/api/search`
- All code in integration will be packaged into final docker and generate excitable
- For services inside Telenav, like Ranking, Oasis, We'd better also build a wiki page like this one: https://github.com/Telenav/osrm-backend/blob/master-telenav/docs/http.md

**Comment by wangyoucao577** [comment]
- yes
- yes
- yes
- yes. 
  - For `routeByOSRM/tableByOSRM`, I think put them into `integration/pkg/api/osrm` may not good enough. They're only request by http, but may have different http parameters and error handling, e.g. timeout, GET/POST, target server, etc. Maybe put them into another package `integration/service/osrm/...` will be better. 
- I'll suggest to put API definition in `integration/pkg/api/search` if necessary. For something like `PlaceSearch`, put them into `integration/service/search/...`. 
- yes. All `golang` binaries will be packaged into docker automatically, don't need to do anything else.  
- Agree. `osrm-ranking` don't need it since `osrm-ranking` use OSRM APIs directly. It's good to have it for the new `oasis`.

**Comment by CodeBear801** [comment]
Thanks for your comments.  Very helpful.
