### ISSUE TITLE
Move components under `integration` to `integration/service`

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#254]
@wangyoucao577 

Proposal:
Move following components and adjust includes in cmd and related packages
- `integration/oasis` to `integration/service/oasis`
   + Put `integration/oasis/osrmconnector` in `integration/service/osrmconnector`
   + Put `integration/oasis/searchconnector` in `integration/service/searchconnector`
   + Other service could use this one to communicate with osrm and search
- `integration/ranking*` to `integration/service/ranking*`
- `integration/traffic*` to `integration/service/traffic*`
- <del>`intergration/wayids2nodeids` to `integration/service/wayid2nodeids`
- <del>`integration/wayidsmap` to `integration/service/wayidsmap`
- <del>`integration/osmfiles` to `integration/service/osmfiles`

After this, the remaining folders under `integration` are
- cmd
- doc
- graph   // may be this one could be moved to pkg/api or service
- pkg
- service
- util

In my local, I create several tools for ad-hoc testing, such as `osrm-connector-test` and `search-connector-test`, can I upload them to `cmd` or `cmd/tools`

**Comment by wangyoucao577** [comment]
I feel some confusion on the word `service`. Are all the functional packages services? E.g., `wayids2nodeids ` and  `wayidsmap` seem only functional packages, can we call them service?        

Moreover, `graph` is not good enough so far, I prefer to move it into `util` instead of `api`. For all tools, I'll suggest to put them into `cmd/` directly, no necessary to have more folder level I think.

**Comment by CodeBear801** [comment]
- `graph` -> `util` is good
- All tools into `cmd/` for now
- Let's only put reasonable package to `service` for now.  What about `wayids2nodeids` and `wayidsmap` go to `util`, it provides functionality for us.
