### ISSUE TITLE
Allowing u-turns in two way segments

### ISSUE THREAD

**Issue by safe-bug** [Telenav/osrm-backend#369]
Hello
First of all I'm so happy that I found an active repository of OSRM and I'm impressed by the functionalities that you're working on to add to OSRM.

I have an issue with OSRM in two way segments where the route can be both in forward direction (according to bearing) and a turn around and continuing backward direction. It seems that according to the driving rules in Europe it's not a legal action to do a u-turn in the middle of a two way segment but in my country it's a legal action and the resulting route of OSRM is kind of strange for our users.

Can you help me how can I fix this? Or maybe enable it?

Thanks

**Comment by wangyoucao577** [comment]
Could you please show us the concrete case that you met and the route you expected? Better to have pictures of your case, and location where the problem actually occurred.

**Comment by safe-bug** [comment]
@wangyoucao577 Thanks for your reply. This is a [snapshot of the issue](https://i.imgur.com/gzZwfoY.png) and this is the [sample request](https://routing.openstreetmap.de/routed-car/route/v1/driving/59.31930541992188,36.30861951701905;59.35344457626342,36.31224631086058?overview=false&alternatives=true&steps=true&bearings=270,90;0,180&hints=;AMAegR3AHoFNAAAABwAAAM4CAACWAAAAkL7OQsR4DEHux25E8_10Q00AAAAHAAAAzgIAAJYAAAC6HAEAU6mJAwEVKgJlqYkDthQqAhcA7wTtwdmi) 

The user is driving towards the left side so the response route of OSRM is to go to the end of the road, turn around and come back. But the expected and legal response is to turn around at the start of the route and continue.

I've tried changing [this line](https://github.com/Project-OSRM/osrm-backend/blob/57ed232423f34743ba80c06eb157b51d9cf52d94/src/extractor/intersection/intersection_analysis.cpp#L532) to always return true, but I'm not sure if it breaks other things as I haven't tested it much. What do you suggest?

I'm from Iran :)

**Comment by wangyoucao577** [comment]
Interesting issue. Firstly it's not caused by restriction since there's no turn restrictions around the origin/destination point of your request by checking [osm map](https://www.openstreetmap.org/way/392067484#map=15/36.3062/59.3226). Furthermore, the roads here mostly will be compressed as a single edge by [OSRM's graph processing](https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/understanding_osrm_graph_representation.md#basic-changes-of-convert-osm-to-osrm-edge-expanded-graph). So once you add `bearings` in request, the route can only go ahead to the [deadend that allows u-turn](https://github.com/Project-OSRM/osrm-backend/blob/57ed232423f34743ba80c06eb157b51d9cf52d94/src/extractor/intersection/intersection_analysis.cpp#L537).       
From my perspective, it's not recommended to fix it in the routing engine since it may break OSRM's graph abstraction. Is it possible to remove the `bearings` option from your request?

**Comment by safe-bug** [comment]
I think it's not possible to remove the bearings, the driver requests a routing inside the navigator while driving and so it has a bearing. If I totally remove the bearings from the navigator it makes other issues, such as giving routes backwards the drivers direction while driving. Do you have any idea? 

The issue isn't just related to these long and two way roads, it's also an issue in residential streets. Again it is legal to turn around in the middle of a residential and not to go at the end of a deadend for it.

**Comment by wangyoucao577** [comment]
I have no idea at the moment. Did you ask this issue on https://github.com/Project-OSRM/osrm-backend? Any other suggestion from other authors/contributors?

**Comment by safe-bug** [comment]
Yes, I've asked this in osrm-backend repository before ([here](https://github.com/Project-OSRM/osrm-backend/issues/5260)) but the only idea was the same as you said to remove the bearing.
I think you are also using osrm for a navigator, how do you use the bearing? Do you even use it?
