### ISSUE TITLE
Improvement and Pipeline for K8s Deployment

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#93]
Currently we already succeed to use container(etc: docker) and orchestration tool(etc: kubernetes) to deploy OSRM(Including binary, data, live traffic solution).      

But we still need to improve the deployment: 
- release pipeline for dev/stage env; 
- mapdata should be injected during container startup; 

Let's use this issue to track and discuss these improvements.

**Comment by wangyoucao577** [comment]
This release pipeline is heavily depends on telenav's internal running environment and how we collaborate with each other. I think it's not that meaningful for community. Also, the "inject mapdata during container startup" seems not that important since we run "engine+mapdata" together docker image very well.

**Comment by nhaskins01** [comment]
You should most likely be using osrm-datastore, that way you can easily swap the data without any sort of rolling update. K8s supports IPC as well so it should work in theory. I have it working in an AWS ECS setup on my own EC2 server. This also allows you to setup a DaemonSet for the worker/osrm-datastore so you can have multiple nodes but only have one datastore running on them and then you can spin up as many routing containers as you need on those nodes for scaling purposes.

**Comment by wangyoucao577** [comment]
@nhaskins01  You're right! If you look at https://github.com/Telenav/osrm-backend/blob/c9e9cc98e395fb1fc164741da63abcfc7d2172ae/docker-orchestration/osrm-backend/docker-entrypoint.sh#L65, `osrm-datastore` already in place. We have launched it in our AWS EKS Clusters and it works well. This approach is much better than the rolling update: easier to deploy, easier to maintain.      

But I have a question on **This also allows you to setup a DaemonSet for the worker/osrm-datastore so you can have multiple nodes but only have one datastore running on them and then you can spin up as many routing containers as you need on those nodes for scaling purposes.**, do you mean run multiple containers together to share 1 data set via shared memory?

**Comment by nhaskins01** [comment]
Ah got it, I was looking at the k8s rolling update file. 

yeah exactly. So you would have a DaemonSet run the worker container which should be customizing the data and loading it into the datastore, which would be available to all pods on that node via IPC resources/shared memory. 

So imagine 2 nodes dedicated to OSRM and each running the DaemonSet. Now you can spin up as many osrm-routed instances as you want and they will connect to the shared memory segment, you also are removing a single point of failure by having 2 nodes and removing a single point of failure on the pods by having more than 1 on each node. 

However, im not sure about the overhead of the containers and if you are better off running one osrm-routed container per node and giving it all of the nodes resources. If this is the case, then I would just probably run 3 nodes with it. 

One improvement I think you can make is doing the data transformation in a single place instead of in each application. So you could have a worker on a cron or just constantly running that does the osrm-customize and uploads to s3, the osrm-routed/datastore application now just has to download the data from s3 and load it into the datastore(be sure to use a lock file so you dont have the customize process uploading files while the routed/datastore process is downloading them). Doing the customize on the application container can cause a large spike in RAM usage and other resources which can lead to performance issues according to the osrm-backend team.

Overall this is a really solid looking project though, mine looks very similar to how you have yours setup, im working on migrating it to k8s now and updating the setup a bit to take advantage of a few things I didnt think of in the beginning.

**Comment by wangyoucao577** [comment]
The DaemonSet you said only can solve the single point failure issue that if `osrm-routed` crashes. However, from my testing it's quite stable. So it may be overhead than benifit, and you have to spend time on it.      
A simple way to prevent single point failure issue is to run two replicas(PODs) per deployment in Kubernetes, both process and node failure can be covered.       

I run this approach on 16 vcpus instance , and customize cpu has been limited by 12 to balance the customize and route performance. The data transformation makes sense to improve it, but s3 may be too slow. EFS might work, but there're more stuff that need to care about it: all the customziing, uploading, downloading and datastore take time. It's valuable to have a try if need that a many instances setup.
